### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by paperc07** [vlmaier/marvel-snap-scrapr#7]
How do we get this to work and pull all the images?

**Comment by vlmaier** [comment]
Just uncomment this line of code: https://github.com/vlmaier/marvel-snap-scrapr/blob/main/scrapr.py#L45

After the script is done downloading you will find a directory called `marvel-snap-cards`. It contains all found Marvel SNAP character images.

**Comment by paperc07** [comment]
ok ty trying to see if I can then use those to help with a bot we are working on

**Comment by vlmaier** [comment]
I see. Good luck with your project.

**Comment by vlmaier** [comment]
> ok ty trying to see if I can then use those to help with a bot we are working on
> 
> paper@Natures-Organic-HOME MINGW64 ~/Desktop/marvel-snap-scrapr-main $ python scrapr.py Traceback (most recent call last): File "C:\Users\paper\Desktop\marvel-snap-scrapr-main\scrapr.py", line 2, in import requests ModuleNotFoundError: No module named 'requests'

You need to run `pip install -r requirements.txt` to install the required modules.

**Comment by paperc07** [comment]
yeah I did and installed all 3 now I got this as the latest

$ python scrapr.py
C:\Users\paper\Desktop\marvel-snap-scrapr-main\scrapr.py:13: DeprecationWarning: headless property is deprecated, instead use add_argument('--headless') or add_argument('--headless=new')
  chrome_options.headless = True


EDIT: NVM them are all there TY!

**Comment by vlmaier** [comment]
You are welcome. I close the issue then 👍🏻
